services:
  api1:
    image: cleissonb/rinha-backend-2026-rinha-api:v0.0.8
    platform: linux/amd64
    environment:
      API_ADDR: 0.0.0.0:8080
      API_FD_SOCKET: /sockets/api1.sock
      RESOURCES_DIR: /app/resources
      RINHA_SEARCH_MODE: keyfirst
      RINHA_NET_MAX_THREADS: "512"
      RINHA_RTS: ${RINHA_RTS:--N2 -A24m -I0 -ki4k --nonmoving-gc}
      RINHA_EARLY_DISTANCE_MILLI: ${EARLY:-140}
      RINHA_PROBE_PARTITIONS: ${PROBE:-12}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    expose:
      - "8080"
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    cpus: 0.42
    mem_limit: 150m
    restart: unless-stopped

  api2:
    image: cleissonb/rinha-backend-2026-rinha-api:v0.0.8
    platform: linux/amd64
    environment:
      API_ADDR: 0.0.0.0:8080
      API_FD_SOCKET: /sockets/api2.sock
      RESOURCES_DIR: /app/resources
      RINHA_SEARCH_MODE: keyfirst
      RINHA_NET_MAX_THREADS: "512"
      RINHA_RTS: ${RINHA_RTS:--N2 -A24m -I0 -ki4k --nonmoving-gc}
      RINHA_EARLY_DISTANCE_MILLI: ${EARLY:-140}
      RINHA_PROBE_PARTITIONS: ${PROBE:-12}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    expose:
      - "8080"
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    cpus: 0.42
    mem_limit: 150m
    restart: unless-stopped

  lb:
    image: cleissonb/rinha-backend-2026-rinha-lb:v0.0.8
    platform: linux/amd64
    environment:
      LB_ADDR: 0.0.0.0:9999
      BACKEND1: api1:8080
      BACKEND2: api2:8080
      FD_BACKEND1: /sockets/api1.sock
      FD_BACKEND2: /sockets/api2.sock
      RINHA_NET_MAX_THREADS: "512"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    cpus: 0.16
    mem_limit: 40m
    restart: unless-stopped

networks:
  rinha:
    driver: bridge

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
