services:
  api1:
    image: cleissonb/rinha-backend-2026-rinha-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    platform: linux/amd64
    environment:
      API_ADDR: 0.0.0.0:8080
      API_FD_SOCKET: /sockets/api1.sock
      RESOURCES_DIR: /app/resources
      KNN_CANDIDATES: "128"
      RINHA_PROBE: "3"
      RINHA_RESIDUAL_REFINE: "1"
      RINHA_NET_MAX_THREADS: "512"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    expose:
      - "8080"
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    cpus: 0.485
    mem_limit: 150m
    restart: unless-stopped

  api2:
    image: cleissonb/rinha-backend-2026-rinha-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    platform: linux/amd64
    environment:
      API_ADDR: 0.0.0.0:8080
      API_FD_SOCKET: /sockets/api2.sock
      RESOURCES_DIR: /app/resources
      KNN_CANDIDATES: "128"
      RINHA_PROBE: "3"
      RINHA_RESIDUAL_REFINE: "1"
      RINHA_NET_MAX_THREADS: "512"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    expose:
      - "8080"
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    cpus: 0.485
    mem_limit: 150m
    restart: unless-stopped

  lb:
    image: cleissonb/rinha-backend-2026-rinha-lb:latest
    build:
      context: .
      dockerfile: Dockerfile.lb
    platform: linux/amd64
    environment:
      LB_ADDR: 0.0.0.0:9999
      BACKEND1: api1:8080
      BACKEND2: api2:8080
      FD_BACKEND1: /sockets/api1.sock
      FD_BACKEND2: /sockets/api2.sock
      RINHA_NET_MAX_THREADS: "512"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    cpus: 0.03
    mem_limit: 40m
    restart: unless-stopped

networks:
  rinha:
    driver: bridge

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
